# Generated by Django 3.2.12 on 2024-10-13 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(help_text='Brief description of your company or website.')),
                ('contact_email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number.', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a vehicle class (e.g. SUV, Sedan, Minivan, etc.)', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(default='Unknown', help_text="What is the customer's phone number", max_length=11)),
                ('address', models.TextField(default='Unknown', help_text="What is the customer's address?", max_length=300)),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_provider', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'phone_num')},
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuName', models.CharField(max_length=20)),
                ('carModel', models.CharField(help_text='Enter a brief description of the Car(IE: Model)', max_length=100)),
                ('vehicleType', models.ForeignKey(help_text='Select a vehicle type for this car', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinNum', models.CharField(help_text='Unique VIN for this particular vehicle in the garage', max_length=17)),
                ('modelYear', models.CharField(help_text='What year is this model?', max_length=4)),
                ('color', models.CharField(help_text="What is the common name of the vehicle's color and also its paint code.", max_length=50)),
                ('license_plate', models.CharField(help_text='What is the plate for this vehicle', max_length=12)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('O', 'Owner has vehicle in their possession'), ('S', 'Scrap or Parts vehicle'), ('A', 'Available'), ('R', 'Ready for release to owner')], default='A', help_text='Car Status', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.carmake')),
                ('mechanic_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.owner')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
