# Generated by Django 3.2.12 on 2024-09-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a vehicle class (e.g. SUV, Sedan, Minivan, etc.)', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuName', models.CharField(max_length=20)),
                ('carModel', models.CharField(help_text='Enter a brief description of the Car(IE: Model)', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.owner')),
                ('vehicletype', models.ForeignKey(help_text='Select a vehicle type for this car', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinNum', models.CharField(help_text='Unique VIN for this particular car in the garage', max_length=17)),
                ('modelYear', models.CharField(help_text='What year is this model?', max_length=4)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('O', 'Owner has vehicle in their possession'), ('S', 'Scrap or Parts vehicle'), ('A', 'Available'), ('R', 'Ready for release to owner')], default='A', help_text='Car Status', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.carmake')),
            ],
        ),
    ]
