# Generated by Django 3.2.12 on 2024-10-06 01:02

from django.db import migrations
from django.contrib.auth.models import Group

def create_customer_group(apps, schema_editor):
    Group.objects.get_or_create(name='Customer')

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20241004_1202'),
    ]

    operations = [
        migrations.RunPython(create_customer_group),
    ]
