# Generated by Django 3.2.12 on 2024-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_feedback_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
