# Generated by Django 3.2.12 on 2024-10-17 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_feedback_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='color',
            field=models.CharField(help_text="Enter the common name of the vehicle's color (e.g., Red) and its paint code.", max_length=50),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Enter the date by which the vehicle should be returned. Leave blank if not applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='license_plate',
            field=models.CharField(help_text="Enter the vehicle's license plate number. Maximum length is 12 characters.", max_length=12),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='mechanic_stat',
            field=models.ForeignKey(blank=True, help_text='Select the mechanic assigned to this vehicle, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='modelYear',
            field=models.CharField(help_text='Enter the year this car model was manufactured (e.g., 2020).', max_length=4),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('M', 'Maintenance'), ('O', 'Owner has vehicle in their possession'), ('S', 'Scrap or Parts vehicle'), ('A', 'Available'), ('R', 'Ready for release to owner')], default='A', help_text='Select the current status of the car: M (Maintenance), O (Owner has vehicle), S (Scrap), A (Available), R (Ready for release).', max_length=1),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='vinNum',
            field=models.CharField(help_text='Enter the Vehicle Identification Number (VIN) for this vehicle. It must be exactly 17 characters.', max_length=17),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='carModel',
            field=models.CharField(help_text='Enter the car model (e.g., Camry, F-150).', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='manuName',
            field=models.CharField(help_text='Enter the name of the car manufacturer (e.g., Toyota, Ford).', max_length=20),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='vehicleType',
            field=models.ForeignKey(help_text='Select the type of vehicle this car belongs to (e.g., SUV, Sedan).', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.vehicletype'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('site', 'Site Feedback'), ('personnel', 'Personnel Feedback'), ('shop', 'Shop Feedback'), ('general', 'General Feedback')], default='general', help_text='Select the category that best describes your feedback.', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='Enter your feedback or comments here.'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='about_us',
            field=models.TextField(help_text='Enter a brief description of your company or website to display in the footer.'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_email',
            field=models.EmailField(help_text='Enter the contact email address that users can reach out to.', max_length=254),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_phone',
            field=models.CharField(help_text='Enter the contact phone number for customer inquiries.', max_length=15),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(help_text="Enter the owner's address. This can be a full street address.", max_length=300),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(help_text="Enter the owner's first name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='has_insurance',
            field=models.BooleanField(default=False, help_text='Check if the owner has insurance for their vehicle.'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='insurance_policy_number',
            field=models.CharField(blank=True, default='Unknown', help_text='Enter the insurance policy number (if applicable).', max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='insurance_provider',
            field=models.CharField(blank=True, default='Unknown', help_text='Enter the name of the insurance provider (if applicable).', max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(help_text="Enter the owner's last name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_num',
            field=models.CharField(help_text="Enter the owner's phone number (e.g., 1234567890). Maximum 10 digits.", max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(help_text='Enter a vehicle class (e.g. SUV, Sedan, Minivan, etc.) This will categorize your vehicles.', max_length=20, unique=True),
        ),
    ]
