# Generated by Django 3.2.12 on 2024-10-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20241017_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='vinNum',
            field=models.CharField(blank=True, help_text='Enter the Vehicle Identification Number (VIN) for this vehicle. It must be exactly 17 characters.', max_length=17, null=True),
        ),
    ]
