# Generated by Django 3.2.12 on 2024-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(help_text='Brief description of your company or website.')),
                ('contact_email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number.', max_length=15)),
            ],
        ),
    ]
